[theme]
base="light"
# (you can add overrides below if you want)
primaryColor="#1f77b4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"
baseRadius = "large"
